# Macro file for the initialization of PRadSim in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2

/pradsim/det/target/material Ta
/pradsim/det/target/radius 25.00 mm
/pradsim/det/target/halfl 0.0005 mm

#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting


/control/execute vis.mac
